### ISSUE TITLE
Lost headers from options if doing a post with json body => leads to unexpected 401 Unauthorized.

### ISSUE THREAD

**Issue by ncoder** [sindresorhus/ky#480] opened 2023-01-06 00:50 UTC
For some reason, on one environment (not all), this section of code manages to drop the headers that I had set in the options.

I've got a pretty horrible environment, (sveltekit running in an azure function host emulator). but I'm still posting this in case someone else on the internet finds this and upvotes this issue.

```ts
		if (this._options.json !== undefined) {
			this._options.body = JSON.stringify(this._options.json);
			this.request.headers.set('content-type', this._options.headers.get('content-type') ?? 'application/json');
			this.request = new globalThis.Request(this.request, {body: this._options.body});
		}
```

**Comment by Caesarovich** [comment] 2023-01-07 15:36
@ncoder I could not reproduce the issue, could you tell us more ? Did you have any error message ? Can we see your code ?

Here's my reproduction attempt:

```js
import ky from "ky";
import body from 'raw-body'
import express from "express";


const parseRawBody = async (request) => {
	const buffer = await body(request);
	return buffer.toString();
};


const app = express();


app.post("/", async function (req, res) {
	console.log('SERVER: ');
	console.log(req.headers);
	console.log('SERVER: ' + await parseRawBody(req));
	res.send("RECEIVED BY CLIENT");
});

app.listen(3000);

console.log('CLIENT: ' + await ky.post("http://localhost:3000", {
        json: {a: 'bee'},
        headers: {
	        helloBoy: 'supBuddy'
        }
}).text());

```

Output: 
```
SERVER: 
{
  host: 'localhost:3000',
  connection: 'keep-alive',
  'content-type': 'application/json',
  helloboy: 'supBuddy',
  accept: 'text/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'undici',
  'accept-encoding': 'gzip, deflate',
  'content-length': '11'
}
SERVER: {"a":"bee"}
CLIENT: RECEIVED BY CLIENT
```
We can see that no headers set in the options were overridden.

**Comment by ncoder** [comment] 2023-01-07 19:49
So this will be difficult to reproduce, as my code (identical) worked fine if executed in a normal environment.
I reproduced this error only when i ran under azure function enumation, as well as on a azure static web app itself (obviously i'm talking about the hosted function part).

So there must be something special about that environment that causes trouble.

Unfortunately it's really not that easy to setup such an test environment.

---
as for more details about the problem... It's really what i described. The Request had the headers until it was re-created for the POST call.  I can only think of two options:
1) Whatever node version was running is the problem
2) Some special monkey patching going on for azure serverless function execution.

**Comment by Caesarovich** [comment] 2023-01-13 03:10
@ncoder My guess is that the issue is from the `fetch` function provided by your environment. I would suggest to try and use the ky's [`fetch` option](https://github.com/sindresorhus/ky#fetch) to define a proven fetch function.

For example I tried [`node-fetch`](https://www.npmjs.com/package/node-fetch) using the polyfill method to patch the global object:

```js
import ky from "ky";
import body from 'raw-body'
import express from "express";
import fetch, {
  Headers,
  Request,
  Response,
} from 'node-fetch'

globalThis.fetch = fetch
globalThis.Headers = Headers
globalThis.Request = Request
globalThis.Response = Response

const parseRawBody = async (request) => {
	const buffer = await body(request);
	return buffer.toString();
};


const app = express();


app.post("/", async function (req, res) {
	console.log('SERVER: ');
	console.log(req.headers);
	console.log('SERVER: ' + await parseRawBody(req));
	res.send("RECEIVED BY CLIENT");
});

app.listen(3000);

console.log('CLIENT: ' + await ky.post
("http://localhost:3000/", {
        json: {a: 'bee'},
        fetch,
        headers: {
	        helloBoy: 'supBuddy'
        }
}).text());
```

Output:
```
SERVER: 
{
  host: 'localhost:3000',
  connection: 'keep-alive',
  'content-type': 'application/json',
  helloboy: 'supBuddy',
  accept: 'text/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'undici',
  'accept-encoding': 'gzip, deflate',
  'content-length': '11'
}
SERVER: {"a":"bee"}
CLIENT: RECEIVED BY CLIENT
```

> Notice that it was not necessary to use Ky's fetch option here since we replaced the function itself in the globalThis object. It is just for the example.

As we can see it reproduced the same behavior as previously but using `node-fetch` as the fetch function instead of NodeJS's built-in one.
This could help to ensure a proper fetch implementation across multiple environments. **Please note that node-fetch might not be the one library suited for your needs, perhaps you need to dig in NPM and search for other polymorphic fetch implementations.**

**Comment by Caesarovich** [comment] 2023-01-13 03:11
I hope this helped, if everything is ok for you I think we can safely say that this issue is not directly related to Ky. So feel free to close it whenever you can.

**Comment by ncoder** [comment] 2023-01-13 17:11
It did! Thanks for looking into this. I may be the only one in the universe who hit this, But if there's someone else, maybe they'll find this thread and it'll help them out as well.

I'm sure you're probably right, azure's function environment must be fiddling with the fetch method. My guess is probably for instrumentation purposes. It has this ability to track and report on upstream dependency requests done by your service.

**Closed** 2023-01-13 17:12 UTC
