### ISSUE TITLE
Fix signal.throwIfAborted is not a function (it is undefined) on React Native using Expo, Hermes

### ISSUE THREAD

**Issue by notDemian** [sindresorhus/ky#659] opened 2024-12-05 03:13 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `ky@1.7.2` for the project I'm working on.

i am working in a react native app using expo and hermes, and for some reason (i couldnt find any issue related) the signals coming from an abort controller hasnt implemented the `throwIfAborted` method, then throws `signal.throwIfAborted is not a function (it is undefined)`
modifying the ky/distribution/utils/delay,js file solved the problem
i guess this has to be related to hermes as the implementation of the method is missing, i dont know if using other engine like jsc fix the issue but i hope this is helpful to anyone

relevant info

package.json
```json
{
  "expo": "~52.0.11",
  "react-native": "0.76.3",
  "ky": "^1.7.2",
}
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ky/distribution/utils/delay.js b/node_modules/ky/distribution/utils/delay.js
index 7df9a1f..1f1750b 100644
--- a/node_modules/ky/distribution/utils/delay.js
+++ b/node_modules/ky/distribution/utils/delay.js
@@ -2,7 +2,14 @@
 export default async function delay(ms, { signal }) {
     return new Promise((resolve, reject) => {
         if (signal) {
-            signal.throwIfAborted();
+            if(typeof signal.throwIfAborted === 'function') {
+                signal.throwIfAborted();
+            } else {
+                if (signal.aborted) {
+                    reject(signal.reason);
+                    return;
+                }
+            }
             signal.addEventListener('abort', abortHandler, { once: true });
         }
         function abortHandler() {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sholladay** [comment] 2024-12-05 05:30
Duplicate of #588

Sorry you're running into this, and thanks for the clear issue description, but in the future please check the existing issues before reporting.

While the solution is easy, we don't plan to fix this because it's a weird omission on React Native's part. `throwIfAborted()` has been supported everywhere for years. It's not an obscure or new API, nor is it hard to implement. You should ask the RN team why they haven't gotten around to it.

If it turns out that there's a good reason, please let us know and we will consider adding a workaround. But most likely it's just not on their radar.

**Closed** 2024-12-05 05:30 UTC
