### ISSUE TITLE
await ky.get('url').json() or .text() is an empty string sometimes

### ISSUE THREAD

**Issue by tnfAngel** [sindresorhus/ky#563] opened 2024-03-03 15:13 UTC
Bun 1.0.29 (a146856d)

## await ky.get('url').json() or .text() is likely to fail on bun

Response
![img](https://github.com/sindresorhus/ky/assets/57068341/d157367d-84d4-4e26-9b61-d032cc4c9a82)

Empty string when doing .json() or .text() 
![img](https://github.com/sindresorhus/ky/assets/57068341/1cfdb3fb-e98d-447e-81af-d3df05eb3a12)

**Comment by vibl** [comment] 2024-03-15 09:49
I have this problem too. About 1 in 6 requests returns an empty response body.

If I add the following line in the `function_()` function (line 19), I always get a response body with the cloned request, even when the main request response doesn't return a body.

```javascript
        let response = await ky._fetch();
        // This prints an empty body in about 1 in 6 requests
         response.clone().blob().then(blob => blob.text()).then( str => console.log("Blob for main request:", str));
        // This always prints a body
        fetch(this.request.clone(), {}).then( res => res.blob()).then(blob => blob.text()).then( str => console.log("Blob for cloned request:", str));
       
```

**Comment by sausaw** [comment] 2024-05-04 12:43
@vibl I think this issue got fixed in Bun v1.1.7. I no longer get empty string as a response. I was facing the same issue in Bun v1.1.6.

**Comment by Drakeoon** [comment] 2024-05-14 18:38
Got the same problem recently. In my case adding double `await` helped for some reason:

```tsx
# ❌ before
const userDetails = await client.get(`users/${id}`).json();

# ✅ after
const userDetails = await (await client.get(`users/${id}`)).json();
```

Really don't know why that helps, but after this change I've never experienced any problems. I'm also using `bun@1.1.3` (as mentioned above by @vibl) and `ky@1.2.2`

**Comment by ershisan99** [comment] 2024-06-21 10:23
> Got the same problem recently. In my case adding double `await` helped for some reason:
> 
> ```tsx
> # ❌ before
> const userDetails = await client.get(`users/${id}`).json();
> 
> # ✅ after
> const userDetails = await (await client.get(`users/${id}`)).json();
> ```
> 
> Really don't know why that helps, but after this change I've never experienced any problems. I'm also using `bun@1.1.3` (as mentioned above by @vibl) and `ky@1.2.2`

That's brilliant, thank you very much! I was starting to lose my mind over this

**Comment by sholladay** [comment] 2024-06-22 18:27
I don't know what the actual problem is, but if the "double await" example is a 100% reliable workaround, then that would seem to indicate that the problem is related to our body method shortcut function:

https://github.com/sindresorhus/ky/blob/585ebcb80545d784b31033e5a70326a0eb202468/source/core/Ky.ts#L81-L107

Whereas a single await calls `.json()` on the Ky promise and thus uses our shortcut function, the double await example calls `.json()` on the `response` (just like you would with `fetch()`) and does _not_ use our shortcut function. The difference should be minor, as all `promise.json()` does is set the [`Accept` request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) and runs a few parsing rules for convenience.

That said, the implementation does do two notable things:
1. It calls [`response.clone()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/clone), which has proven to be problematic in some cases.
2. In order to make it possible for `promise.json()` to set the `Accept` header before the request is sent even though it's a separate function call from `ky()`, we [delay the fetch](https://github.com/sindresorhus/ky/blob/585ebcb80545d784b31033e5a70326a0eb202468/source/core/Ky.ts#L32). It wouldn't surprise me if this was causing some kind of race condition.

**Comment by tnfAngel** [comment] 2024-06-30 20:32
double await works fine, but it's not nice to have to always write this workaround, this bug should be fixed

**Comment by sholladay** [comment] 2024-06-30 22:13
> this bug should be fixed

To do that, we need one of the following:
1. Someone needs to provide a reproducible failing test case so that I or another maintainer can investigate the problem. Even if the problem is intermittent, the test case can just repeat itself until failure.
2. Investigate it yourself by adding some console logs or debugger statements to the part of the code that I linked to in my last comment. Find out which of those `if` statements is being triggered that return an empty string and then determine how the values are different than you expected.

On my end of things, I don't use Bun and I cannot reproduce this bug in Deno or Node.

Here was my attempt to reproduce it:

```js
import ky from 'https://unpkg.com/ky@1.3';

const url = 'https://jsonplaceholder.typicode.com/todos/1';
const maxAttempts = 300;
let attemptCount = 0;
let json;

while (attemptCount < maxAttempts) {
    attemptCount++;

    json = await ky(url).json();

    if (!json) {
        break;
    }
}

if (json) {
    console.log(`Success: receieved JSON ${attemptCount} times`);
    console.log(json);
}
else {
    console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
    console.error(json);
}
```

**Comment by tnfAngel** [comment] 2024-07-01 00:51
> > this bug should be fixed
> 
> To do that, we need one of the following:
> 
>     1. Someone needs to provide a reproducible failing test case so that I or another maintainer can investigate the problem. Even if the problem is intermittent, the test case can just repeat itself until failure.
> 
>     2. Investigate it yourself by adding some console logs or debugger statements to the part of the code that I linked to in my last comment. Find out which of those `if` statements is being triggered that return an empty string and then determine how the values are different than you expected.
> 
> 
> On my end of things, I don't use Bun and I cannot reproduce this bug in Deno or Node.
> 
> Here was my attempt to reproduce it:
> 
> ```js
> import ky from 'https://unpkg.com/ky@1.3';
> 
> const url = 'https://jsonplaceholder.typicode.com/todos/1';
> const maxAttempts = 300;
> let attemptCount = 0;
> let json;
> 
> while (attemptCount < maxAttempts) {
>     attemptCount++;
> 
>     json = await ky(url).json();
> 
>     if (!json) {
>         break;
>     }
> }
> 
> if (json) {
>     console.log(`Success: receieved JSON ${attemptCount} times`);
>     console.log(json);
> }
> else {
>     console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
>     console.error(json);
> }
> ```

I can reproduce this exact code on bun v1.1.17 (latest)
![image](https://github.com/sindresorhus/ky/assets/57068341/c0c2e0d4-6211-4ba2-9c84-b4deffb22d4b)
Although it doesn't seem to be that common in this piece of code, in my production application when I reported it the chances of failure were ~70-80%, I don't know what factor makes this more common or not, but it was very frequent (and it still is if I do it without the workaround)

**Comment by sholladay** [comment] 2024-07-01 02:49
Yeah, this is looking like a Bun issue. It will likely reproduce with `fetch` instead of Ky when triggered just the right way, probably as a result of using `.clone()`.

Plain `fetch`:
```js
const url = 'https://jsonplaceholder.typicode.com/todos/1';
const maxAttempts = 300;
let attemptCount = 0;
let json;

while (attemptCount < maxAttempts) {
    attemptCount++;

    const response = await fetch(url);
    json = await response.json();

    if (!json) {
        break;
    }
}

if (json) {
    console.log(`Success: receieved JSON ${attemptCount} times`);
    console.log(json);
}
else {
    console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
    console.error(json);
}
```

With cloned response:
```js
const url = 'https://jsonplaceholder.typicode.com/todos/1';
const maxAttempts = 300;
let attemptCount = 0;
let json;

while (attemptCount < maxAttempts) {
    attemptCount++;

    const response = await fetch(url);
    json = await response.clone().json();

    if (!json) {
        break;
    }
}

if (json) {
    console.log(`Success: receieved JSON ${attemptCount} times`);
    console.log(json);
}
else {
    console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
    console.error(json);
}
```

With double cloned response:
```js
const url = 'https://jsonplaceholder.typicode.com/todos/1';
const maxAttempts = 300;
let attemptCount = 0;
let json;

while (attemptCount < maxAttempts) {
    attemptCount++;

    const response = await fetch(url);
    json = await response.clone().clone().json();

    if (!json) {
        break;
    }
}

if (json) {
    console.log(`Success: receieved JSON ${attemptCount} times`);
    console.log(json);
}
else {
    console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
    console.error(json);
}
```

With double cloned response and decoded array buffer:
```js
const url = 'https://jsonplaceholder.typicode.com/todos/1';
const maxAttempts = 300;
let attemptCount = 0;
let json;

while (attemptCount < maxAttempts) {
    attemptCount++;

    const response = await fetch(url);
    const buffer = await response.clone().clone().arrayBuffer();
    json = new TextDecoder().decode(buffer);

    if (json) {
        json = JSON.parse(json);
    }
    else {
        break;
    }
}

if (json) {
    console.log(`Success: receieved JSON ${attemptCount} times`);
    console.log(json);
}
else {
    console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
    console.error(json);
}
```

**Comment by tnfAngel** [comment] 2024-07-01 09:26
> Yeah, this is looking like a Bun issue. It will likely reproduce with `fetch` instead of Ky when triggered just the right way, probably as a result of using `.clone()`.
> 
> Plain `fetch`:
> 
> ```js
> const url = 'https://jsonplaceholder.typicode.com/todos/1';
> const maxAttempts = 300;
> let attemptCount = 0;
> let json;
> 
> while (attemptCount < maxAttempts) {
>     attemptCount++;
> 
>     const response = await fetch(url);
>     json = await response.json();
> 
>     if (!json) {
>         break;
>     }
> }
> 
> if (json) {
>     console.log(`Success: receieved JSON ${attemptCount} times`);
>     console.log(json);
> }
> else {
>     console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
>     console.error(json);
> }
> ```
> 
> With cloned response:
> 
> ```js
> const url = 'https://jsonplaceholder.typicode.com/todos/1';
> const maxAttempts = 300;
> let attemptCount = 0;
> let json;
> 
> while (attemptCount < maxAttempts) {
>     attemptCount++;
> 
>     const response = await fetch(url);
>     json = await response.clone().json();
> 
>     if (!json) {
>         break;
>     }
> }
> 
> if (json) {
>     console.log(`Success: receieved JSON ${attemptCount} times`);
>     console.log(json);
> }
> else {
>     console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
>     console.error(json);
> }
> ```
> 
> With double cloned response:
> 
> ```js
> const url = 'https://jsonplaceholder.typicode.com/todos/1';
> const maxAttempts = 300;
> let attemptCount = 0;
> let json;
> 
> while (attemptCount < maxAttempts) {
>     attemptCount++;
> 
>     const response = await fetch(url);
>     json = await response.clone().clone().json();
> 
>     if (!json) {
>         break;
>     }
> }
> 
> if (json) {
>     console.log(`Success: receieved JSON ${attemptCount} times`);
>     console.log(json);
> }
> else {
>     console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
>     console.error(json);
> }
> ```
> 
> With double cloned response and decoded array buffer:
> 
> ```js
> const url = 'https://jsonplaceholder.typicode.com/todos/1';
> const maxAttempts = 300;
> let attemptCount = 0;
> let json;
> 
> while (attemptCount < maxAttempts) {
>     attemptCount++;
> 
>     const response = await fetch(url);
>     const buffer = await response.clone().clone().arrayBuffer();
>     json = new TextDecoder().decode(buffer);
> 
>     if (json) {
>         json = JSON.parse(json);
>     }
>     else {
>         break;
>     }
> }
> 
> if (json) {
>     console.log(`Success: receieved JSON ${attemptCount} times`);
>     console.log(json);
> }
> else {
>     console.error(`Failure: received empty JSON on attempt ${attemptCount}`);
>     console.error(json);
> }
> ```

I have tried all the cases and the only one that has not given an error is the first one, so it is the .clone()

**Comment by sholladay** [comment] 2024-07-01 16:32
Yeah, this appears to be a [known issue](https://github.com/oven-sh/bun/issues/6348) in Bun.

There is a PR to fix it which has been open for a long time:
https://github.com/oven-sh/bun/pull/6468

**Closed by sholladay** 2024-07-01 16:32 UTC

**Comment by devunt** [comment] 2024-08-13 22:50
For future references: there's corresponding issue opened in bun repo: https://github.com/oven-sh/bun/issues/11682.
