### ISSUE TITLE
TimeoutError is thrown even for successful requests

### ISSUE THREAD

**Issue by arty-name** [sindresorhus/ky#120] opened 2019-04-08 10:28 UTC
It looks like Ky throws the TimeoutError unconditionally, even when the request completed without errors.

**Steps to reproduce:** 

1. Open any webpage
2. Open developer tools
3. Activate "Pause on exceptions" and "Pause on caught exceptions"
4. Execute following code in the console: 
    `import('https://unpkg.com/ky').then(module => module.default('/')).then(console.log)`
5. Wait 10 seconds

**Expected result:**

No error is thrown

**Actual result:**

The Response is logged in the console, indicating successful request. However after the timeout of 10 seconds the debugger pauses on the line with `throw new TimeoutError();` 

PS: if in your test case there’s an actual request error adjust the path from '/' to something which doesn’t cause request error.

**Comment by sholladay** [comment] 2019-04-08 13:39
Thanks for the high quality bug report, @arty-name!

This is a duplicate of #91. See that issue for details.

**Closed by sholladay** 2019-04-08 13:39 UTC

**Comment by arty-name** [comment] 2019-04-08 13:42
Oh, it’s title wasn’t quite clear about that... Thanks for the quick response anyway!
