### ISSUE TITLE
Using with http-proxy-middleware

### ISSUE THREAD

**Issue by popuguytheparrot** [sindresorhus/ky#178] opened 2019-09-30 18:20 UTC
Hi. I have problem with ky.js and proxy. No requests in browser when i use ky.create and prefixUrl

I tried changes url in prefix like `localhost:3000/api` or `localhost:3000` and in

```js
const terminalsUrl = 'api/terminals';
or like this
const terminalUrl = '/terminal';
```

`ky.config.js`
![image](https://user-images.githubusercontent.com/19804652/65904809-dc910780-e3c7-11e9-9241-fb26125dbf3f.png)

`proxy.server.js`
![image](https://user-images.githubusercontent.com/19804652/65904686-9cca2000-e3c7-11e9-934d-6fedcb6961cf.png)

**Comment by kevva** [comment] 2019-09-30 19:08
None of your URLs in the screenshot points to `/api` where your proxy listens.

**Comment by sholladay** [comment] 2019-09-30 19:21
Can you please show a reproducible code example that I can run on my own machine? Otherwise it's hard to debug this.

From just the snippets you posted, it sounds like maybe `ky` is never actually getting called.

**Comment by sholladay** [comment] 2019-10-01 07:50
I'm curious what will happen if you do:

```js
const terminalsUrl = 'api';
```

I think @kevva made a good point that your input URL is probably not matching your proxy route on the backend. I don't know if your proxy is handling only `/api`, or if it's handling `/api/*` (all paths beginning with `/api/`). It's worth double-checking that it's the latter and not the former, otherwise `api/terminals` won't work.

**Comment by kevva** [comment] 2019-10-01 08:51
`http-proxy-middleware` should catch all routes starting with `/api`. However, I'm pretty sure this is not an issue with `ky`.

**Comment by popuguytheparrot** [comment] 2019-10-01 09:57
@sholladay 
https://gist.github.com/popuguytheparrot/f7f8c6a7cd454be72f52ddab66bc8370

**Comment by sholladay** [comment] 2019-10-01 11:46
Perfect, thanks for the repro. I forked your gist, fixed the problems, and pushed the changes. I also ran the proxy and verified the fix.

https://gist.github.com/sholladay/7316505d5f7cc5a9fc596973e1cb4c7d/revisions

There were two problems with the code:

1. Your `prefixUrl` did not include `/api/v1/`. Thus, the request was going to `http://localhost:3000/employees` instead of `http://localhost:3000/api/v1/employees`. The proxy was returning a 404 Not Found error, because that's what `http://dummy.restapiexample.com/employees` returns to the proxy for a JSON request. The correct URL is `http://dummy.restapiexample.com/api/v1/employees`. I just added the API prefix to the `prefixUrl`.
2. In `index.js`, you were _returning_ the `console.log` function and not calling it. That means even if the request succeeded, you never would have seen the data. I changed it to `.then(console.log)`, which is equivalent to `.then(data => console.log(data))`.

With those changes, I was able to log the employees data successfully.

If you need any further help on this, the best course of action would be to ask a question on [StackOverflow](https://stackoverflow.com/) and post the link here. In the meantime, I'm going to close this, as it's not a problem with Ky.

Good luck! 🙌

**Closed by sholladay** 2019-10-01 11:46 UTC
