### ISSUE TITLE
 Can external "fetch dependency be injected to ky"

### ISSUE THREAD

**Issue by guillaume-chervet** [sindresorhus/ky#269] opened 2020-07-06 09:59 UTC
I would like to inject an enhanced fetch to ky (fetch is a dependency to ky).

In order to use with https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/context-fetch in a "functionnal way"

Is it possible to do something like : 

`
const parsed = await ky(fetch).post('https://example.com', {json: {foo: true}}).json();
`

?

Regards,

Guillaume

**Comment by sholladay** [comment] 2020-07-06 11:28
Would it be okay if it were just a normal Ky option, as below?

```js
const parsed = await ky.post('https://example.com', {fetch, json: {foo: true}}).json();
```

```js
const myKy = ky.extend({fetch});
const parsed = await myKy.post('https://example.com', {json: {foo: true}}).json();
```

**Comment by guillaume-chervet** [comment] 2020-07-06 15:21
Yes, it is

**Comment by Skayo** [comment] 2020-07-17 13:01
Isn't this a duplicate of #56?

**Comment by sholladay** [comment] 2020-07-17 13:56
@Skayo 

Yes, you're correct, it is. And the concerns that Sindre expressed there are still valid.

However, it's worth noting that since then:
 - Ky gained an additional co-maintainer (me :))
 - We have made it easier to override our globals, including `fetch` (e.g. https://github.com/sindresorhus/ky/commit/f107e7b92d90e4b0287846a49ba3f30d9b9ca648 and PR https://github.com/sindresorhus/ky/pull/153)
 - We created [ky-universal](https://github.com/sindresorhus/ky-universal) which could potentially benefit from this feature
 - Ky has stabilized a lot, we haven't tagged a 1.0 release yet but I've been happily using it in production for quite some time

It's definitely worth reconsidering this.

**Comment by Skayo** [comment] 2020-07-17 15:43
Yeah that is true.
Might even need this for a project myself. 
Do you know how much work this would be?
Maybe I'll do a PR...

**Comment by sholladay** [comment] 2020-07-17 16:41
It should be pretty easy. You would need to update [this part](https://github.com/sindresorhus/ky/blob/6e0294035bb32675e92bd471176e0543b63e774e/index.js#L180) of the code where we execute the fetch, so that it would be something like `options.fetch()` instead of `globals.fetch()`. You would set the default value for `fetch` to `globals.fetch` at the top of the Ky constructor, where we set our other option defaults.

**Comment by Skayo** [comment] 2020-07-17 18:00
@guillaume-chervet @sholladay 
Check out #273!

**Closed** 2020-07-20 19:57 UTC
Labels: enhancement, help wanted
