### ISSUE TITLE
Recent Ky Update No Longer Works With Next.js

### ISSUE THREAD

**Issue by LuisOsta** [sindresorhus/ky#348] opened 2021-05-16 23:29 UTC
I recently noticed while trying to get the `ky-universal` package working with Next.js that the latest version of `Ky` doesn't work at all. Even though it recently worked just fine.

Starting in version **'0.28.0'** and onwards, the error:
```
 error - ./services/requests.ts:1:0
client_1  | Module not found: Can't resolve 'ky'
client_1  | > 1 | import ky from "ky";
client_1  |   2 | 
client_1  |   3 | const prefixUrl = process.env.NEXT_PUBLIC_API_URL;
client_1  |   4 | export const AUTH_HEADER_NAME = "Authorization";
```
Appears in relation to ky. But it works perfectly fine in version **'0.27.1'**. Looking at the changelog, I'm not entirely sure what it could be.

Here's my next.config.js for context:
```
const withTM = require("next-transpile-modules")(["ky"]);

module.exports = withTM({
  future: {
    webpack5: false,
  },
});
```

**Comment by LuisOsta** [comment] 2021-05-16 23:31
My guess is that it may have been related to the move to Typescript, but that seems like a weird thing to cause a module resolution bug.

**Comment by dakshshah96** [comment] 2021-05-17 08:33
Duplicate of #340.

**Comment by sholladay** [comment] 2021-05-17 18:16
Indeed, this is a duplicate. You can try PR #342 to see if that fixes it for you. Feedback on that PR is welcome, especially if it doesn't work for you.

**Closed by sholladay** 2021-05-17 18:16 UTC
