### ISSUE TITLE
0.32.2 breaking on Cloudflare Workers

### ISSUE THREAD

**Issue by probablykasper** [sindresorhus/ky#453] opened 2022-09-09 05:17 UTC
ky 0.31.2 seems to have a breaking change that causes it to not work on Cloudflare Workers:
```
Uncaught Error: To use the new ReadableStream() constructor, enable the
  streams_enable_constructors feature flag.
    at index.js:2678:13
    at index.js:2687:3
```

Tried searching through the build output, and found that in v0.31.1 there are 4 results for `ReadableStream`, while v0.31.2 has 7

**Comment by parafeu** [comment] 2022-09-15 08:47
I have the same problem but not on Cloudflare Workers. The only temporary solution was to rollback to v0.31.1.

I'm using Vite 3.1.1

**Comment by RihanArfan** [comment] 2022-09-15 18:45
Creating a `wrangler.toml` file (or appending to it) with `compatibility_flags = ["streams_enable_constructors"]` fixed this for me.

I'm using Miniflare to develop locally (using `wrangler dev ...`), not tried deploying yet.

Source: https://developers.cloudflare.com/workers/platform/changelog/#2021-12-10

**Comment by Caesarovich** [comment] 2023-01-13 03:22
@parafeu @probablykasper is the issue still ongoing, or did the recent releases / environment tweaks given by @RihanArfan fix the issue ?

**Comment by probablykasper** [comment] 2023-01-13 03:47
The compatbility flag @RihanArfan suggested works great. I haven't tested if recent versions work without it

**Comment by sholladay** [comment] 2023-02-16 09:23
Looks like this problem is caused by the fact that [we feature test](https://github.com/sindresorhus/ky/blob/740732c78aad97e9aec199e9871bdbf0ae29b805/source/core/constants.ts#L4-L22) for `duplex` support in the `Request` constructor and in order to do that, we call `ReadableStream()` if it's available. Prior to v0.31.2 we were only ever calling `ReadableStream()` if you used stream related features like `onDownloadProgress`. But now, we always test for `ReadableStream`'s existence no matter what, and if it's there, we use it. In other environments, that either succeeds or fails silently, and either way, Ky gets the information it needs. But in Workers, it throws an error.

Personally, I would argue that Workers shouldn't be exposing `ReadableStream` if it's unusable. So I'm going to close this for now. Feel free to propose a specific change to Ky if you think it's necessary. We could wrap our feature tests in a `try` / `catch` but that's not generally necessary given how they are written and it would hide legitimate bugs in our code, so I would prefer not to.

**Closed by sholladay** 2023-02-16 09:23 UTC

**Comment by kentonv** [comment] 2023-02-20 20:55
For what it's worth, this compatibility flag in Workers has been on by default since 2022-11-30. If you set your worker's `compatibility_date` to that date or later, then the flag will be on, and the class's constructor will be usable. I highly recommend keeping your Worker's `compatibility_date` current -- using an old date means requesting bug-for-bug compatibility with old versions of the Workers platform. The lack of a constructor on ReadableStream is one such bug.

The reason `ReadableStream` existed but with no constructor before this date is because Workers has actually supported `ReadableStream` for 5+ years as part of the Fetch API, but did not supported _constructing_ a stream object independent of the API until last year. Since introduction the constructor was a very large change to the implementation of `ReadableStream`, it was placed behind a flag for fear of breaking people.
