### ISSUE TITLE
1ms delay before fetch causing issues with New Relic SPA logger

### ISSUE THREAD

**Issue by smblee** [sindresorhus/ky#345] opened 2021-05-14 07:23 UTC
I found a finicky bug where the implementation detail of ky waiting 1ms before fetch (https://github.com/sindresorhus/ky/pull/118) is actually not allowing New Relic Pro+SPA to log AJAX requests. 

I am not sure of the full detail of why this may be happening - but this is how i have verified it's being caused by 1ms setTimeout.

- I tried using native `fetch` and `wretch` library instead of `ky`. New Relic was able to pick up all AJAX requests for both scenarios.
- I tried using `axios` that relies on XHR requests. New Relic was also able to pick this up.
- I used `ky` but manually commented out the `await delay(1);` from ky inside `node_modules`, and it started working (granted, the `.json` function fails, but the request was getting picked up)

Do you guys have any idea why this may be happening?

If so, do you have suggestions on how to get around this issue?

**Comment by smblee** [comment] 2021-05-14 07:29
https://github.com/sindresorhus/ky/issues/220 linking this issue for more exposure

**Comment by smblee** [comment] 2021-05-14 07:55
I was able to reproduce this by using native fetch and adding the same `delay` call right beforehand.

```
 await delay(1);
  const apiResponse = await (
    await fetch('api/my-endpoint', {
      headers: { 'Content-Type': 'application/json' },
    })
  ).json();
```

At this point, it might be an issues i need to take it up to New Relic.. Super strange behavior.

**Comment by smblee** [comment] 2021-05-14 08:24
I further confirmed that it indeed is more of an issue with New Relic. They seem to not log requests when there are other promises happening "around them".

I tried adding a promise right before fetching using libraries that _does work_ with New Relic logging, and immediately, it stopped working.

```
await delay(1);
await fetch(...);
```

```
await delay(1);
await axios(...)
```

```
await fetch(...endpoint1);
await fetch(...endpoint2);
```

none of these were logging to New Relic.

**Comment by sholladay** [comment] 2021-05-14 18:37
Great debugging, thanks for the details. If you have an idea about how we could remove the delay, we would gladly consider it. But at the moment, I'm not aware of any way to do that without making major changes to the API (which we can also discuss but I think it's unlikely to happen).

Given the above and the fact that this is reproducible without Ky, I'm going to close this issue for now. Will reopen if anything actionable comes up. Depending on New Relic's response, maybe we could provide a way to opt-out of the delay.

**Closed** 2021-05-14 18:37 UTC

**Comment by lukeupup** [comment] 2021-05-25 11:35
Hi,

Much thanks to the great work from @smblee. We've encountered exactly the same problem with NewRelic. I found that we can fix the problem by replacing the `delay(1)` by `setTimeout` (because it will remove the other promise around the `fetch`). Although it looks ugly on code level, it might be the lightest way to resolve the problem without changing any API of `ky`.

I will open a PR for this. Hopefully we can reopen this ticket and have further discussion. Thanks.

**Comment by lukeupup** [comment] 2021-05-26 12:09
Hi @smblee,
If you can see this message, could you help to test the code in #351? If it can both our problem, I think we can have a relatively easy fix without waiting for new relic. Thank you.

**Comment by darrinmn9** [comment] 2021-05-28 17:13
@smblee you're just using the newrelic browser agent SPA right? I saw many open issues about the NR agent not supporting `fetch`? Am I wrong? I was manually implementing ajax tracking with my app (that uses `ky`) and the NR browser agent. Did you have any special configuration? This would be a great relief if simply upgrading `ky` will fix the NR ajax tracking.

**Comment by smblee** [comment] 2021-05-28 17:47
@darrinmn9 Their documentation honestly isn't great especially around SPA/Pro browser agent. Some of their pages mention they don't support `fetch` but that's only for the basic agent. AFAIK from my quick 20 minutes of testing with the fix, everything seemed to be getting shipped up to New Relic as expected (tested with query browser for AjaxRequest table, and their prebuilt dashboard)
