### ISSUE TITLE
custom error handler

### ISSUE THREAD

**Issue by lyyourc** [sindresorhus/ky#148] opened 2019-07-03 07:08 UTC
## Background

According to the [source code](https://github.com/sindresorhus/ky/blob/master/index.js#L105), `HttpError` uses `response.statusText` as default value of the `message` property. 

**And I want to change the behavior 🤨**

## My try

I try to modify the `response.statusText` in the hooks,

```js
hooks: {
	afterResponse: [
		response => {
			return new Response('A different response', {
				status: 200,
			 	// ❌ It would fail if using chinese characters instead of English
				statusText: 'some chinese characters'
			})
		}
	]
}
```

but result in an error:

```
TypeError: Failed to construct 'Response': Value is not a valid ByteString
```

I also try to set `throwHttpErrors` as `false` and throw a custom Error:

```js
hooks: {
	afterResponse: [
		response => {
			throw new MyCustomHttpError()
		}
	]
}
```

As error threw, the `response` doesn't return, so I can't access `response` which is `undefined`:

```js
// ❌Uncaught TypeError: Cannot read property 'json' of undefined
myApi().then(response => response.json())
```

**Comment by sholladay** [comment] 2019-07-03 13:22
Sorry, but this has nothing to do with Ky. I can reproduce by simply executing only the snippet below (without Ky):
```
new Response('hello', {
    status     : 200,
    statusText : '漢字'
})
```

In Chrome:

```js
TypeError: Failed to construct 'Response': Value is not a valid ByteString.
```

In Firefox:

```js
TypeError: Cannot convert string to ByteString because the character at index 0 has value 28450 which is greater than 255.
```

As you can see, Firefox provides a much more detailed and helpful error message. The problem is that only some characters are allowed in the status message. Specifically, code points 0-255 (also known as U+0000 to U+00FF). For a table of the allowed characters, see: https://www.utf8-chartable.de/unicode-utf8-table.pl

As for why more code points are not supported, I have no idea. I assume this is due to legacy constraints for compatibility with very old HTTP implementations.

Unfortunately, this is not something we can fix or work around, so I'm going to close this issue.

**Closed by sholladay** 2019-07-03 13:22 UTC

**Comment by gutenye** [comment] 2019-07-12 09:36
@sholladay then `throw new MyCustomHttpError()` is the way to go, but ky will [retry the request automatically unless you disable it](https://github.com/sindresorhus/ky/issues/149#issuecomment-509010002)

Do you think we should disable `retry` on custom error

**Comment by sholladay** [comment] 2019-07-12 21:05
We'll, it's not just HTTP response errors that should be retried. Network failures should be retried as well, among others. I don't really see a problem with retrying all errors. Do you?

**Comment by gutenye** [comment] 2019-07-13 11:53
> Network failures should be retried as well

That's true, but should do like got does, catch specific errors not all https://github.com/sindresorhus/got/blob/master/source/normalize-arguments.ts#L244

> I don't really see a problem with retrying all errors

I want to throw a Chinese error message in the hooks, but I don't want to retry it. And there's no way to do it.

**Comment by sholladay** [comment] 2019-07-13 20:07
> throw a Chinese error message

There is no issue with Chinese when it comes to throwing errors. The problem that @lyyourc ran into with Chinese was due to the fact that the `Response` class does not support Chinese characters in the `statusText` property. That is a legitimate issue as far as I'm concerned, one that should probably be brought to the attention of WHATWG, although I assume there's a historical reason for it. However, no such limitation exists in the `Error` class.

> but don't want a retry

Then throw an error with a status code that won't be retried. As long as you avoid using the `Response` class, you can put Chinese characters in the message.

```js
throw new ky.HTTPError({ status: 400, statusText : 'You can put Chinese here' });
```

This solution is not particularly elegant, and I do agree that we should improve our error filtering logic. `ReferenceError`s and `TypeError`s should not be retried, certainly. I'm not sure about plain `Error`s, though. Anyway, I hope that solution works for you, for now.
