### ISSUE TITLE
`error.response.clone()` trigger error

### ISSUE THREAD

**Issue by Airkro** [sindresorhus/ky#263] opened 2020-06-30 01:24 UTC
https://github.com/sindresorhus/ky/blob/master/index.js#L398

Sometimes `error.response` return `null`.

I have to do this to make it work:

```diff
- response: error.response.clone(),
+ response: error.response ? error.response.clone() : null,
```

**Comment by sholladay** [comment] 2020-06-30 01:32
Duplicate of #251

**Closed by sholladay** 2020-06-30 01:32 UTC
