### ISSUE TITLE
ky in typescript don't work

### ISSUE THREAD

**Issue by c0ncentus** [sindresorhus/ky#216] opened 2019-12-11 13:56 UTC
```Typescript    
    export default createInstance();
    ^^^^^^
    SyntaxError: Unexpected token export
    > 4 | import ky from "ky";
```

This issue has closed. for me it's bug if i can't easily make 
```Typescript
import ky from "ky";
```

👎

**Comment by c0ncentus** [comment] 2019-12-11 14:12
```TypeError: globals.Request is not a constructor
    at new Ky (c:\WORKBRENCH\AUTRE\DockerLabs_Front\node_modules\ky\umd.js:243:19)
    at Function.ky.<computed> [as get] (c:\WORKBRENCH\AUTRE\DockerLabs_Front\node_modules\ky\umd.js:456:37)
    at c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:4:25
    at step (c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:33:23)
    at Object.next (c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:14:53)
    at c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:4:12)
    at c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:3:13
    at getById (c:\WORKBRENCH\AUTRE\DockerLabs_Front\Request\Article.ts:5:7)
```


with this 

```Typescript
import ky from 'ky/umd';
function getById(a: string, b: string, c: string) {
    return (async () => {
        return await ky.get('https://jsonplaceholder.typicode.com/todos/1').json()
    })();
}
//getAll('https://jsonplaceholder.typicode.com', 'todos').then((res) => { console.log(res) })
getById('https://jsonplaceholder.typicode.com', 'todos', '1')
    .then((res) => { console.log(res) })
    .catch((e:any)=>{
        console.log(e)
    });
```

**Comment by szmarczak** [comment] 2019-12-11 14:12
Duplicate of #170

**Closed by szmarczak** 2019-12-11 14:12 UTC
