### ISSUE TITLE
Ky does not seem to handle large JSON responses well

### ISSUE THREAD

**Issue by smonn** [sindresorhus/ky#432] opened 2022-03-08 21:33 UTC
Ran into this issue and had a very hard time debugging it as Ky seemed to timeout randomly instead of throwing an error or doing the right thing(tm). Another library that rhymes with [BIOS](https://axios-http.com/) handles this without issue (granted, that one does not use fetch).

Easily reproduced by adding this test in `test/main.ts`:

```ts
test('GET large JSON response', async t => {
	t.plan(1)
	t.timeout(5000)

	const size = 50_000
	const json = {
		a_list: [...Array.from({length: size})].map(() => 'a'),
	};

	const server = await createHttpTestServer();
	server.get('/', (_request, response) => {
		response.json(json);
	});

	console.log('large_json.start', Date.now())
	const responseJson = await ky
		.get(server.url)
		.json();
	// The tests seem to "pass", but this line is never logged
	// Reduce the `size` above to ~10_000 and you see both messages being logged
	console.log('large_json.end', Date.now())

	t.deepEqual(responseJson, json);

	await server.close();
});
```

**Comment by afraser** [comment] 2022-03-09 01:18
+100 This took us _days_ to track down since our production instance was the only instance set up with large enough data to produce the behavior described.

**Comment by sholladay** [comment] 2022-03-09 02:57
Thank you for the failing test case. I am able to reproduce it and that is very helpful.

This clearly has something to do with the implementation of our body method shortcuts.

This test passes:

```js
test('GET large JSON response', async t => {
	t.plan(1)
	t.timeout(5000)

	const size = 50_000
	const json = {
		a_list: [...Array.from({length: size})].map(() => 'a'),
	};

	const server = await createHttpTestServer();
	server.get('/', (_request, response) => {
		response.json(json);
	});

	console.log('large_json.start', Date.now())
	const response = await ky.get(server.url);
	const responseJson = await response.json();
	// The tests seem to "pass", but this line is never logged
	// Reduce the `size` above to ~10_000 and you see both messages being logged
	console.log('large_json.end', Date.now())

	t.deepEqual(responseJson, json);

	await server.close();
});
```

**Comment by smonn** [comment] 2022-03-09 14:06
Thanks, that makes sense. This would be in Node.js 16, specifically server-side Next.js which, I believe, provides a poly fill for fetch. Therefore, we're not using ky-universal. I'll update this comment with exact version numbers in a bit.

**Comment by sholladay** [comment] 2022-03-09 19:01
Could you try your app with the latest Node 17.5 or higher with the `--experimental-fetch` flag, which [has `fetch()` built in](https://fusebit.io/blog/node-fetch/), and see if the behavior is any different? I'm not sure if the Next.js polyfills are implemented in such a way to avoid overwriting these globals when they already exist, but hopefully that's the case. If so, and the built in `response.clone()` behaves better, then that may just solve the problem for you.

I tried running the test case with `--experimental-fetch` but it errored without running. Looks like that flag may not be supported in worker threads yet, which AVA uses to create an isolated environment for each test file.

```sh
❯ npx ava test/main.ts --node-arguments='--expiremental-fetch'

  ✖ Internal error
  Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --expiremental-fetch
  Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --expiremental-fetch
      at new NodeError (node:internal/errors:372:5)
      at new Worker (node:internal/worker:191:13)
      at createWorker (/Users/sholladay/Code/personal/ky/node_modules/ava/lib/fork.js:16:12)
      at module.exports (/Users/sholladay/Code/personal/ky/node_modules/ava/lib/fork.js:74:39)
      at pMap.concurrency.concurrency (/Users/sholladay/Code/personal/ky/node_modules/ava/lib/api.js:234:20)
      at /Users/sholladay/Code/personal/ky/node_modules/p-map/index.js:57:28
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ─
```

Still, from what I can tell the built in implementation does seems to solve the problem. For example, this call to the `/photos` endpoint never returns when using our polyfills in `test/require.ts` but it succeeds when using `--experimental-fetch`.

```js
import ky from 'ky';

console.log('large_json.start', Date.now());
const responseJson = await ky
    .get('https://jsonplaceholder.typicode.com/photos')
    .json();
console.log('large_json.end', Date.now());
```

**Comment by smonn** [comment] 2022-03-16 02:14
I haven't had a chance to try this myself yet, but I think it's fair to close this and reference the workaround (meaning no `ky.get('/...').json()`), using Node.js 17.5+, or avoiding Ky in Node.js altogether. On our end, we'll avoid Ky in Node.js for now. Thanks!

**Comment by sholladay** [comment] 2022-03-23 08:08
Alright, will close this since it's an upstream issue. FWIW, most of Ky's features still work fine when awaiting the response first before calling `.json()`. Hopefully the workaround isn't too intrusive. There's also [got](https://github.com/sindresorhus/got) for people who need a truly Node first implementation with a somewhat similar API.

**Closed by sholladay** 2022-03-23 08:08 UTC

**Comment by cah4a** [comment] 2023-12-08 08:34
Run into this on bun v1.0.14.

**Comment by austinm911** [comment] 2024-04-14 20:17
> Alright, will close this since it's an upstream issue. FWIW, most of Ky's features still work fine when awaiting the response first before calling `.json()`. Hopefully the workaround isn't too intrusive. There's also [got](https://github.com/sindresorhus/got) for people who need a truly Node first implementation with a similar API.

@sholladay you should add a comment to the documentation. I using calling .json() on ky and spent a few hours trying to debug why I wasn't receiving data until i found this

**Comment by sholladay** [comment] 2024-06-23 05:59
@austinm911 what environment were you using? I believe `response.clone()` is working better in Deno and Node these days, at least in terms of hanging the response stream. I've never used Bun, so can't speak to that.

I would be fine with a note in the documentation, although I don't think it will realistically save anyone time. Feel free to send a PR if you want.
