### ISSUE TITLE
Compatibility with chrome 53 

### ISSUE THREAD

**Issue by Airkro** [sindresorhus/ky#262] opened 2020-06-30 01:19 UTC
Something wrong with this line:

https://github.com/sindresorhus/ky/blob/master/index.js#L52

I have to do this to make it work:

```diff
  const mergeHeaders = (source1, source2) => {
-   const result = new globals.Headers(source1);
+   const result = source1 ? new globals.Headers(source1) : new globals.Headers();
```

**Comment by Airkro** [comment] 2020-06-30 01:28
Might be the same problem:

https://github.com/sindresorhus/ky/issues/260

If so, close this.

**Comment by sholladay** [comment] 2020-06-30 01:37
Duplicate of #250

**Comment by sholladay** [comment] 2020-06-30 01:37
Chrome 53 is four years old. How has it not been updated? 😄

**Closed by sholladay** 2020-06-30 01:37 UTC

**Comment by Airkro** [comment] 2020-06-30 01:40
In my country, It is a sad story, some popular application has built-in chromium core.
