### ISSUE TITLE
afterResponse hook causes response Promise to hang

### ISSUE THREAD

**Issue by exogen** [sindresorhus/ky#135] opened 2019-05-15 01:32 UTC
Here's a simple repro: https://github.com/exogen/ky-afterResponse-repro

This doesn't seem to happen for every request; I suspect it might have something to do with the response body size. I tried a couple small public JSON API demos before I landed on a GraphQL endpoint that reproduced the behavior.

Under certain conditions, simply including an `afterResponse` hook causes the response Promise to hang. The hook doesn't have to do anything; it can be a no-op function or just return the same cloned response. Removing the hook causes it to start working. Switching to `node-fetch` also works fine.

I wonder if the hook causes the response to be cloned and therefore the Promise as well, making one of them never resolve? Just a thought.

**Comment by sindresorhus** [comment] 2019-08-23 13:55
Duplicate of https://github.com/sindresorhus/ky-universal/issues/8

**Comment by sindresorhus** [comment] 2019-08-23 13:55
Can you post your issue description above as a comment on https://github.com/sindresorhus/ky-universal/issues/8?

**Closed** 2019-09-07 17:05 UTC
