### ISSUE TITLE
.json() method does not execute for failing API response

### ISSUE THREAD

**Issue by jacob-fueled** [sindresorhus/ky#210] opened 2019-11-26 21:15 UTC
Perhaps this is intended, but I see nothing in the README to indicate that the `.json()` helper method _shouldn't_ execute.

```js
ky
  .delete('/does-not-exist')
  .json()
  .then(() => console.log('deleted'))
  .catch(({ errors }) => console.error(errors))
```

With the above, assuming the response body, I expect to see `[{ message: 'Cannot delete a nonexistent resource' }]` in the console. Instead, I get an exception about destructuring (because the argument passed to `catch` is a Ky.HTTPError instance).

The workaround is

```js
ky
  .delete('/does-not-exist')
  .json()
  .then(() => console.log('deleted'))
  .catch({ response }) => response.json())
  .then(console.error)
```

But that seems redundant with the `.json()` in the chain already.

**Comment by sholladay** [comment] 2019-11-27 08:29
We can't just return the parsed response body because in the case of an error, there may not even be a response to parse. Also, it would be weird if the `error` was a simple JSON object. It really has to be an `Error` instance to avoid surprising people and to make it easy to identify, e.g. `error instanceof ky.TimeoutError`.

That said, I would be okay with attaching a property to the error with the parsed object, if available. Something like `error.payload`, to avoid confusing it with the unparsed `body` on `error.response`.

For reference, I do something similar in my custom Ky instance in my apps:

```js
export const apiFetch = ky.extend({
    credentials : 'same-origin',
    mode        : 'same-origin',
    prefixUrl   : '/api/',
    timeout     : 30000,
    hooks       : {
        afterResponse : [
            async (response) => {
                if (response.status === 401) {
                    location.assign('/login?next=' + encodeURIComponent(location.pathname));
                }
                else if (!response.ok) {
                    response.payload = await response.json();
                    return response;
                }
            }
        ]
    }
});
```

**Comment by jacob-fueled** [comment] 2019-11-27 19:11
That makes sense to me! Would it be possible to do that conditionally based on whether `req.json()` was called?

In your custom Ky instance, won't `response.json()` throw an exception (and explode) if there is no response body?

**Comment by sholladay** [comment] 2019-11-27 20:32
> In your custom Ky instance, won't the `await response.json()` throw/explode if there is no response body?

Yes, you are correct about that. However, I use [hapi](https://github.com/hapijs/hapi/) as my web server framework, which always sends back JSON for error responses (4xx and 5xx status codes), even ones that are caused by mistake. The check for `!response.ok` ensures that `await response.json()` is only run for error responses. And we know that we have a `response` there because `afterResponse` only runs when there is a response (i.e. it doesn't run for `ky.TimeoutError`s).

> Would it be possible to do that conditionally based on whether `req.json()` was called?

Yeah, we would only try to parse anything if you explicitly opted into it. We could potentially do something similar for `.formData()`, too, and maybe other body methods.

We would need to decide how to handle missing bodies as well as parsing errors here. Sadly, not everyone is using hapi, so what should happen if you use Ky with `.json()` but the server sends back an error with no body or a body that isn't valid JSON? Silently ignore it or throw an error? Unfortunately, I think throwing an error might be a painful breaking change for our existing users, since it affects which type of error your `.catch()` would receive, basically obscuring what the original error response was. For example, you might receive a parse error instead of a `ky.HTTPError`, which is decidedly less useful. On the other hand, I routinely get frustrated at systems that silently ignore errors, so that isn't great, either, but it's probably the lesser evil here.

**Comment by monolithed** [comment] 2023-11-19 14:07
This behavior is rather peculiar. The semantics of HTTP responses do not always align with the business logic of applications, and in some cases, a 404 status is a valid response. 
In the current implementation, it seems that all concise examples from the documentation need to be wrapped in a try/catch block, which is presented as a downside when comparing it to the standard `fetch` approach.

**Comment by fregante** [comment] 2024-02-24 06:12
This is the consequence of throwing JavaScript errors on HTTP errors: either it's an error _**or**_ you read the response regardless of the HTTP response.

I don’t think there's a solution here, because the `ky.delete()` promise rejects before `.json()` can be executed. Your current solution is likely correct. Here it is rewritten with async/await:


```js
try {
	await ky.delete('/does-not-exist').json();
} catch (error) {
	console.error(await error.response.json())
}
```

**Comment by sholladay** [comment] 2024-08-17 20:05
> in some cases, a 404 status is a valid response

For those cases, you could use our `throwHttpErrors: false` option to treat HTTP error responses as successful, like `fetch()` does.

https://github.com/sindresorhus/ky?tab=readme-ov-file#throwhttperrors

I'm going to close this for now because I don't think we are going to let `ky().json()` determine how the error is parsed. It seems more likely that we will either provide an `error.json()` shortcut for parsing the error in the catch block or auto parse it to `error.payload` based on the `Content-Type` of the response.

**Closed by sholladay** 2024-08-17 20:05 UTC
Labels: enhancement, help wanted

**Comment by pavitra-infocusp** [comment] 2024-12-06 09:30
> ```js
> try {
> 	await ky.delete('/does-not-exist').json();
> } catch (error) {
> 	console.error(await error.response.json())
> }
> ```

This is great because I can handle error types which are different from the success type.
