### ISSUE TITLE
Adding header in beforeRequest downcases it on android

### ISSUE THREAD

**Issue by MaxMaes** [sindresorhus/ky#154] opened 2019-07-24 15:56 UTC
When i add a header via options.headers.set as mentioned in #139 the header name gets downcased on Android:

```
const apiInstance = ky.extend({
            prefixUrl: 'someurl',
            hooks: {
                beforeRequest: [
                    (options: Options) => {
                        options.headers.set('Authorization', this.token); 
                        console.log(options.headers);
                    }
                ]
            }
        });
```
This gives me a the following headers on Android: 
` {authorization: "694nr5DWh..."}`

Andthe following headers on iOS: 
` {Authorization: "694nr5DWh..."}`

I would expect the headers set to respect the casing of the passed parameter.

**Comment by szmarczak** [comment] 2019-07-24 17:33
Duplicate of #105

**Closed by szmarczak** 2019-07-24 17:33 UTC
